// @ts-check
import { createConfigForNuxt } from '@nuxt/eslint-config/flat'
import vuejsAccessibility from 'eslint-plugin-vuejs-accessibility'

export default createConfigForNuxt({
  features: {
    tooling: true,
    stylistic: false, // Prettier handles formatting
  },
  dirs: {
    src: ['./app'],
  },
})
  // C13: accessibility as a LINT gate as well as an E2E one.
  //
  // axe only sees the states a test happens to drive, so a missing label on a
  // branch nobody exercises is invisible to it. The linter reads every template
  // unconditionally — the two catch different things.
  .append(vuejsAccessibility.configs['flat/recommended'])
  .append({
    rules: {
      // Enforce no unused vars (D27 strict mode).
      // Base rule is disabled per typescript-eslint's own guidance: it is not
      // type-aware and false-positives on TS-only constructs such as function-type
      // parameter names in `defineEmits<{ (e: 'x', payload: T): void }>()` call
      // signatures (surfaced by the vendored shadcn-vue Input/Sidebar components).
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'error',
    },
  })
  // Vendored shadcn-vue primitives. `label-has-for` cannot see through a
  // component boundary: these render Reka UI's <Label>, which wires for/id via
  // context at runtime, so the association it is asking for genuinely exists —
  // axe proves it on the rendered page, which is the check that counts.
  //
  // Scoped to this directory rather than switched off globally, and for a
  // second reason beyond the false positive: these files are regenerated by
  // `shadcn-vue add`, so any edit here is lost on the next component install.
  // A hand-fixed vendored file is a fix with an expiry date.
  // Same reasoning extends to `form-control-has-label`: the vendored Textarea
  // primitive (D10/D12 install) receives its label association from the
  // Field/FieldLabel wrapper at the call site via aria-labelledby, which this
  // rule cannot see across the component boundary either.
  .append({
    files: ['app/components/ui/**/*.vue'],
    rules: {
      'vuejs-accessibility/label-has-for': 'off',
      'vuejs-accessibility/form-control-has-label': 'off',
    },
  })
  // GENERATED FILES ARE NOT SOURCE.
  //
  // `types/api.ts` is produced by `openapi-typescript` from `openapi.json`, and
  // `scripts/check-client-drift.sh` regenerates it in CI and diffs byte for
  // byte. Any tool that rewrites it makes a correctly-synced client report as
  // drifted — which is precisely what happened: `eslint --fix` runs on it
  // through lint-staged, a rule reflowed one JSDoc line by a single `*`, and
  // the `Client drift check` step failed on develop for the v0.24.0 release
  // merge-back and again on the next one.
  //
  // `.prettierignore` already covers both files, and prettier honours it even
  // for explicitly-passed paths, so prettier was never the culprit. ESLint had
  // no matching entry at all — this is that entry.
  .append({
    ignores: ['types/api.ts', 'openapi.json'],
  })
